project/FoodApp/urls.py
from django.urls import path
from . import views

app_name='FoodApp'
urlpatterns = [
    path('', views.index,name='index'),
    path('<int:item_id>/',views.detail,name='detail'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('FoodApp.urls')),
]

project/FoodApp/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
      def __str__(self):
            return self.item_name
      
      item_name=models.CharField(max_length=122)
      item_desc=models.CharField(max_length=122)
      item_price=models.IntegerField()
      item_image=models.CharField(max_length=5000,default='https://www.vecteezy.com/vector-art/22058960-no-image-available-icon')

project/FoodApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from FoodApp.models import Item

# Create your views here.
def index(request):
      item_list=Item.objects.all()
      context={
            'item_list':item_list,
      }
      return render(request, 'FoodApp/index.html',context)

def detail(request,item_id):
      item=Item.objects.get(pk=item_id)
      context={
            'item': item,
      }
      return render(request, 'FoodApp/detail.html',context)

project/FoodApp/templates/FoodApp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Base</title>
      <link rel="stylesheet" 
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"  
      />
      <link rel="stylesheet" href='{% static "FoodApp/style.css" %}'>
</head>
<body>
      <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                  <div class="navbar-header">
                        <a class="navbar-brand" href="#" style="font-weight: bold">FoodApp</a>
                  </div>
                  <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href="#">Add Item</a></li>
                        <li><a href="#">Delete Item</a></li>
                        <li><a href="#">Login</a></li>
                  </ul>
            </div>
      </nav>
      {% block body %}
      {% endblock %}
</body>
</html>

project/FoodApp/templates/FoodApp/detail.html
{% extends "FoodApp/base.html" %}

  {% block body %}
 
    <h1 id="item-name">{{ item.item_name }}</h1>
    <h2 id="item-desc">{{ item.item_desc }}</h2>
    <h3 id="item-price">${{ item.item_price }}</h3>

  {% endblock %}

project/FoodApp/templates/FoodApp/index.html
{% extends "FoodApp/base.html" %}

<!DOCTYPE html>
<html lang="en"> 
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Item List</title>
    <link rel="stylesheet" 
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"  
    />
</head>
<body>
    {% block body %}
    {% for item in item_list %}
    <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-4"><img src="{{ item.item_image }}" height="190px" width="280px" class="card"></div>
    <br><br><br>
    <div class="col-md-3"><h3 style="font-family:cursive;font-weight:bold">{{ item.item_name }}</h3></div>
    <br>
    <div class="col-md-3"><a href="{% url 'FoodApp:detail' item.id %}" class="btn btn-success" style="background-color:black;">Details</a></div>
    </div>
    <br><hr><br>
    {% endfor %}
    {% endblock %} 
</body>
</html>  



        
 
     
           
     

project/templates/FoodApp/home.html
<h1>Home</h1>

project/templates/FoodApp/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin:0;
            padding:0;
        }
 
        .container{
            max-width: 400px;
            margin:50px auto;
            background: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
           
        }
        h1{
            text-align: center;
        }
 
        h2{
            text-align: center;
        }
        input[type="text"],
        input[type="email"],
        input[type="tel"],
        input[type="submit"]{
 
            width: 100%;
            padding: 10px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }
        input[type="submit"] {
            background-color: orange;
            color: white;
            padding: 14px 20px;
            margin: 12px 0;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 100%;
            transition: background-color 0.3s;
            font-weight: bold;
        }
        input[type="submit"]:hover{
            background-color: orangered;
        }
    </style>
</head>
<body>
    <h1>User Registeration Form ! </h1>
<div class="container">
                <form action="" method="POST">
                     {% csrf_token %}
                     <label for="username">Username:</label>
                     <input type="text" id="username" name="username" placeholder="Enter username">
         
                     <label for="email">Email:</label>
                     <input type="text" id="email" name="email" placeholder="Enter Your Email">
         
                     <label for="phone">Phone:</label>
                     <input type="text" id="phone" name="phone" placeholder="Enter Your Phone">
 
                     <input type="submit" value="Submit">
 
                </form>
            </div>
        </div>
    </div>        
</div>
</body>
</html>